### ISSUE TITLE
Can't work with preallocated variables.

### ISSUE THREAD

**Issue by ghost** [sehyoun/MATLABAutoDiff#3]
Hello! Thanks for your work.

I have some problem with differentiating a complex function.
Namely, the code:

```
a = myAD( [1]);
b = zeros( 2,2 );
b = a;
```

throws an error:

```
Error using double
Conversion to double from myAD is not possible.
```

**Comment by sehyoun** [comment]
When you "preallocate" `b` in that manner, you are preallocating a double matrix not the myAD object (the Jacobian to be precise). For the particular example, you can do

`
b = repmat(a, 2, 2).*0;
`

But, in general,  you can do
`
b = myAD(zeros(2,2), sparse(4, derivative dimension));
`
where "derivative dimension" the column dimension of the intended Jacobian to preallocate the myAD object.

Let me know if this doesn't answer your question.

PS- This is the only place where you can't use the exact same code with/without autodiff, but unfortunately, I can't fix this behavior without overloading MATLAB intrinsics due to how MATLAB calls functions.

**Comment by ghost** [comment]
Hm... I have a very big project. I probably can replace the preallocation in this particular case, but not over all places where this trick is used 'for speed'.

**Comment by sehyoun** [comment]
Oh yeah, I understand that if it is a big project, that would require a lot of replacements. Unfortunately, this is just a limitation of MATLAB without a good fix.

**Comment by ghost** [comment]
I actually managed to get through this issue just as you told me, but declaring the variable as myAD, instead of zeros.

However, now I'm facing a problem with isnan(). Could you find some time to have a look at it?

It, basically, says 

```
Error using  _|_
Inputs must have the same size.

Error in myAD/isnan (line 5)
y = isnan(x.values) | isnan(sum(x.derivatives,2)).
```
I'm literally doing 
``` index = isnan(x)```

where x is 634x4

And indeed, the vectors don't match in size...

What am I doing wrong?

**Comment by sehyoun** [comment]
Sorry, I forgot to update isnan to allow non-vector shaped values. `isnan` is updated now, so update the AutoDiff, and that problem should be fixed.

**Comment by ghost** [comment]
Thanks! Now it works!
